#!/usr/bin/env python3
import csv
# code: YES / PARTIAL / NO / N/A / UNVERIFIED   -- every YES/PARTIAL cites a source
DIM=["K_GE_3_NATIVE_ACTION_SPACE","MULTICLASS_INTERVENTION","SOURCE_RETAINED_EXPLICIT",
 "GOLD_ARRIVAL_EXPLICIT","OTHER_WRONG_EXPLICIT","DESTINATION_RESOLVED_ACCOUNTING",
 "CHANNEL_DISCOVERY","DETECTOR_OR_ROUTER_GATE","INTERNAL_CAUSAL_INTERVENTION",
 "RANDOM_DIRECTION_CONTROL","REVERSE_CONTROL","WRONG_LAYER_CONTROL",
 "PRESERVATION_ENDPOINT","PROSPECTIVE_FROZEN_CRITERIA","ADMIT_DECLINE_OR_REFUSAL_RULE",
 "POWER_OR_DESIGN_SENSITIVITY_FOR_INTERVENTION_CERTIFICATION"]
P={
"CAST (Lee et al., ICLR 2025)":dict(
  K_GE_3_NATIVE_ACTION_SPACE="NO", MULTICLASS_INTERVENTION="NO",
  SOURCE_RETAINED_EXPLICIT="NO", GOLD_ARRIVAL_EXPLICIT="NO", OTHER_WRONG_EXPLICIT="NO",
  DESTINATION_RESOLVED_ACCOUNTING="NO", CHANNEL_DISCOVERY="NO",
  DETECTOR_OR_ROUTER_GATE="YES", INTERNAL_CAUSAL_INTERVENTION="YES",
  RANDOM_DIRECTION_CONTROL="NO", REVERSE_CONTROL="NO", WRONG_LAYER_CONTROL="NO",
  PRESERVATION_ENDPOINT="PARTIAL", PROSPECTIVE_FROZEN_CRITERIA="NO",
  ADMIT_DECLINE_OR_REFUSAL_RULE="NO",
  POWER_OR_DESIGN_SENSITIVITY_FOR_INTERVENTION_CERTIFICATION="NO"),
"RepE (Zou et al.)":dict(
  K_GE_3_NATIVE_ACTION_SPACE="NO", MULTICLASS_INTERVENTION="NO",
  SOURCE_RETAINED_EXPLICIT="NO", GOLD_ARRIVAL_EXPLICIT="PARTIAL", OTHER_WRONG_EXPLICIT="NO",
  DESTINATION_RESOLVED_ACCOUNTING="NO", CHANNEL_DISCOVERY="NO",
  DETECTOR_OR_ROUTER_GATE="NO", INTERNAL_CAUSAL_INTERVENTION="YES",
  RANDOM_DIRECTION_CONTROL="NO", REVERSE_CONTROL="NO", WRONG_LAYER_CONTROL="NO",
  PRESERVATION_ENDPOINT="PARTIAL", PROSPECTIVE_FROZEN_CRITERIA="NO",
  ADMIT_DECLINE_OR_REFUSAL_RULE="NO",
  POWER_OR_DESIGN_SENSITIVITY_FOR_INTERVENTION_CERTIFICATION="NO"),
"CAA (Rimsky et al.)":dict(
  K_GE_3_NATIVE_ACTION_SPACE="NO", MULTICLASS_INTERVENTION="NO",
  SOURCE_RETAINED_EXPLICIT="NO", GOLD_ARRIVAL_EXPLICIT="NO", OTHER_WRONG_EXPLICIT="NO",
  DESTINATION_RESOLVED_ACCOUNTING="NO", CHANNEL_DISCOVERY="NO",
  DETECTOR_OR_ROUTER_GATE="NO", INTERNAL_CAUSAL_INTERVENTION="YES",
  RANDOM_DIRECTION_CONTROL="NO", REVERSE_CONTROL="NO", WRONG_LAYER_CONTROL="NO",
  PRESERVATION_ENDPOINT="NO", PROSPECTIVE_FROZEN_CRITERIA="NO",
  ADMIT_DECLINE_OR_REFUSAL_RULE="NO",
  POWER_OR_DESIGN_SENSITIVITY_FOR_INTERVENTION_CERTIFICATION="NO"),
"ITI (Li et al., NeurIPS 2023)":dict(
  K_GE_3_NATIVE_ACTION_SPACE="NO", MULTICLASS_INTERVENTION="NO",
  SOURCE_RETAINED_EXPLICIT="NO", GOLD_ARRIVAL_EXPLICIT="NO", OTHER_WRONG_EXPLICIT="NO",
  DESTINATION_RESOLVED_ACCOUNTING="NO", CHANNEL_DISCOVERY="NO",
  DETECTOR_OR_ROUTER_GATE="NO", INTERNAL_CAUSAL_INTERVENTION="YES",
  RANDOM_DIRECTION_CONTROL="YES", REVERSE_CONTROL="NO", WRONG_LAYER_CONTROL="NO",
  PRESERVATION_ENDPOINT="NO", PROSPECTIVE_FROZEN_CRITERIA="NO",
  ADMIT_DECLINE_OR_REFUSAL_RULE="NO",
  POWER_OR_DESIGN_SENSITIVITY_FOR_INTERVENTION_CERTIFICATION="NO"),
"Tan et al. 2024":dict(
  K_GE_3_NATIVE_ACTION_SPACE="NO", MULTICLASS_INTERVENTION="NO",
  SOURCE_RETAINED_EXPLICIT="NO", GOLD_ARRIVAL_EXPLICIT="NO", OTHER_WRONG_EXPLICIT="NO",
  DESTINATION_RESOLVED_ACCOUNTING="NO", CHANNEL_DISCOVERY="NO",
  DETECTOR_OR_ROUTER_GATE="NO", INTERNAL_CAUSAL_INTERVENTION="YES",
  RANDOM_DIRECTION_CONTROL="NO", REVERSE_CONTROL="NO", WRONG_LAYER_CONTROL="NO",
  PRESERVATION_ENDPOINT="NO", PROSPECTIVE_FROZEN_CRITERIA="NO",
  ADMIT_DECLINE_OR_REFUSAL_RULE="NO",
  POWER_OR_DESIGN_SENSITIVITY_FOR_INTERVENTION_CERTIFICATION="PARTIAL"),
"AxBench (Wu et al. 2025)":dict(
  K_GE_3_NATIVE_ACTION_SPACE="NO", MULTICLASS_INTERVENTION="NO",
  SOURCE_RETAINED_EXPLICIT="NO", GOLD_ARRIVAL_EXPLICIT="NO", OTHER_WRONG_EXPLICIT="NO",
  DESTINATION_RESOLVED_ACCOUNTING="NO", CHANNEL_DISCOVERY="NO",
  DETECTOR_OR_ROUTER_GATE="NO", INTERNAL_CAUSAL_INTERVENTION="YES",
  RANDOM_DIRECTION_CONTROL="NO", REVERSE_CONTROL="NO", WRONG_LAYER_CONTROL="NO",
  PRESERVATION_ENDPOINT="NO", PROSPECTIVE_FROZEN_CRITERIA="NO",
  ADMIT_DECLINE_OR_REFUSAL_RULE="NO",
  POWER_OR_DESIGN_SENSITIVITY_FOR_INTERVENTION_CERTIFICATION="NO"),
}
with open("RELATED_WORK_NOVELTY_MATRIX.csv","w",newline="") as f:
    w=csv.writer(f); w.writerow(["paper"]+DIM)
    for p,d in P.items(): w.writerow([p]+[d[k] for k in DIM])
print(f"{'dimension':52}{'YES':>5}{'PARTIAL':>9}{'NO':>5}")
for k in DIM:
    v=[P[p][k] for p in P]
    print(f"{k:52}{v.count('YES'):>5}{v.count('PARTIAL'):>9}{v.count('NO'):>5}")
print(f"\ncorpus n = {len(P)}  (CONVENIENCE SAMPLE — not a prevalence estimate)")
full=[p for p in P if all(P[p][k]=="YES" for k in
     ["DESTINATION_RESOLVED_ACCOUNTING","RANDOM_DIRECTION_CONTROL","PRESERVATION_ENDPOINT",
      "PROSPECTIVE_FROZEN_CRITERIA","ADMIT_DECLINE_OR_REFUSAL_RULE"])]
print(f"FULL_COMBINATION_FOUND: {'YES: '+str(full) if full else 'NO within verified corpus'}")
